config/routes.rb
Rails.application.routes.draw do
  get 'home/:id/index', :controller=>"home", :action=>"show"
  get 'inventory/:id/index', :controller=>"inventories", :action=>"show"
  get "sale/:id/get_json", :controller=>"sale", :action=>"get_json"

  resources :sales do
    collection do
      get :due

    end
  end

  resources :employees

  resources :customers

  resources :inventories

  root 'home#index'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :sales

  def self.search(search)
    if search
      self.where("model like ? OR color like ? OR VIN like ?", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      self.all
    end
  end

  def self.color
    @color
  end

  def self.model
    @model
  end

  def self.vin
    @vin
  end

  def vehicle
    @vehicle = [color, model, vin].join(' ')
  end

  def sale_price
    @sale_price = msrp * 1.1
  end

  def price_with_tax
    @price_with_tax = sale_price * 1.043
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
    # Patching all Listing

    @inventory = Inventory.where(id: params[:id]) if params[:id].present?
    # Find By Id (For paginating, 'where' statement result is Listing ActiveRecord::Relationship )
    @inventories = @inventories.search(params[:search]) if params[:search].present?
    # Search using Keyword
    #@inventories = @inventories.paginate(:page => params[:page], :per_page => 10)
    # Pagination
    @model = Inventory.find_by_model(params[:model]) if params[:model].present?
    # Find model
    @color = Inventory.find_by_color(params[:color]) if params[:color].present?
    @model = Inventory.find_by_VIN(params[:VIN]) if params[:VIN].present?

  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:model, :color, :vin, :msrp)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.select :color, [['','None'],['Beige','Beige'],['Black','Black'],
                          ['Blue','Blue'],['Brown','Brown'],['Gold','Gold'],
                          ['Gray','Gray'],['Green','Green'],['Orange','Orange'],
                          ['Purple','Purple'],['Red','Red'],['Silver','Silver'],
                          ['White','White'],['Yellow','Yellow']] %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :MSRP %><br>
    $<%= f.number_field :msrp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<h4>Current Inventory</h4>

<p id="notice"><%= notice %></p>
<h1>
<%= form_tag inventories_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
</h1>

<p></p>
<table>
  <thead>
    <tr>
      <th>Model</th>
      <th> Color </th>
      <th> VIN </th>
      <th> MSRP </th>
      <th> Sale Price </th>
      <th> Final Total with Tax </th>
      <th colspan="6"><h4><%= link_to '[Add a Vehicle]', new_inventory_path %></h4></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td class="col-md-1"><%= inventory.model %></td>
        <td class="col-md-1"><%= inventory.color %></td>
        <td class="col-md-1"><%= inventory.vin %></td>
        <td class="col-md-1"><%= number_to_currency(inventory.msrp) %></td>
        <td class="col-md-1"><%= number_to_currency(inventory.sale_price) %></td>
        <td ><%= number_to_currency(inventory.price_with_tax) %></td>
        <td ><%= link_to ' View ', inventory %></td>
        <td ><%= link_to ' Edit ', edit_inventory_path(inventory) %></td>
        <td ><%= link_to ' Delete ', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

app/views/inventories/new.html.erb
<h1>Add Vehicle to Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @inventory.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @inventory.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @inventory.vin %>
</p>

<p>
  <strong>MSRP:</strong>
  <%= number_to_currency(@inventory.msrp) %>
</p>

<p>
  <strong>Sale Price:</strong>
  <%= number_to_currency(@inventory.sale_price) %>
</p><p>
  <strong>Price with Tax:</strong>
  <%= number_to_currency(@inventory.price_with_tax) %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>