config/routes.rb
Rails.application.routes.draw do
  get 'home/:id/index', :controller=>"home", :action=>"show"
  get 'inventory/:id/index', :controller=>"inventories", :action=>"show"
  get "sale/:id/get_json", :controller=>"sale", :action=>"get_json"

  resources :sales do
    collection do
      get :due

    end
  end

  resources :employees

  resources :customers

  resources :inventories

  root 'home#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :customer
  belongs_to :employee
  belongs_to :inventory

  scope :status, -> (status) { where status: status }


  def get_json
    json = "{"
    json += "id:'#{Inventory.msrp}'"
    json += "}"
  end

  def self.calculate_loan_table(total, interest_rate, num_years)
    Rails.logger.debug "Inputs: #{total} #{interest_rate} #{num_years}"
    due = []
    (1..(num_years * 12)).each do
      due << (total * (1 + (interest_rate.to_f / 100) * num_years)) / (num_years*12)
    end
    return due
  end

  def interest(total, interest_rate)
    Rails.logger.debug "Inputs: #{total} #{interest_rate}"
    @interest = total * (interest_rate.to_f / 100)
  end

  def vehicle
    @vehicle
  end

  def interest_rate
    @interest_rate
  end

  def total
    @total
  end

  def num_years
    @num_years
  end

  def calculate_loan_table
    return self.class.calculate_loan_table(self.total,self.interest_rate,self.num_years)
  end

  def sum_revenue
    @revenue = Sale.where( :status => ["Sold"]).sum(:total)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def get_json
    sale = Sale.find(params[:sale_id])
    render :json => sale.to_json
  end

  def index
    @sales = Sale.all
    @sales = Sale.where(nil)
    @sales = @sales.status(params[:status]) if params[:status].present?


    @msrp = Inventory.msrp(params[:msrp]) if params[:msrp].present?
    @markup = Inventory.msrp(params[:msrp]) if params[:msrp].present?
    @tax = Sale.markup(params[:markup]) if params[:markup].present?
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    #@loan_array = @sales.calculate_loan_table
    #@sale = Sale.find(params[:id])

    #render :text => sale.vehicle.price_with_tax
  end

  # GET /sales/new
  def new
    @sale = Sale.new

  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def due
    total = params[:total]
    interest_rate = params[:interest_rate]
    num_years = params[:num_years]
    @rate_array = Sale.calculate_loan_table(total.to_f, interest_rate.to_f, num_years.to_f)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      #@sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:vehicle, :total, :customer_id, :employee_id, :status)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle %><br>
    <%= f.collection_select :vehicle, Inventory.all,:vehicle, :vehicle, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total, :remote => true %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all,:id,:name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id, Employee.all,:id,:name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(["Quote", "Sold"]) %>
  </div>
    <div class="field">
      <%= f.label :interest_rate_percentage %><br>
      <%= f.number_field :interest_rate, :remote => true %>
    </div>
    <div class="field">
      <%= f.label :number_of_years %><br>
      <%= f.select :num_years, options_for_select(["3", "4", "5"]), :prompt => true %>
    </div>
<br>
    <div id="loan-table" class="table-format"></div>
    <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/_loan_table.erb
<table class="CSSTableGenerator" width="30%">
  <th><center>Month Number</center></th>
  <th><center>Payment Amount</center></th>
  <% @rate_array.each_with_index do |p,n|  %>
      <tr>
        <td><center><%= n+1 %></center></td>
        <td><center><%= number_to_currency(p) %></center></td>
      </tr>
  <% end %>

</table>

app/views/sales/due.js.erb
$('#loan-table').html("<%= j (render 'loan_table') %>")

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', inventories_path %>

app/views/sales/index.html.erb
<h4>Listing Sales</h4>
<p></p>
<table>
  <thead>
    <tr>
      <th>Vehicle</th>
      <th>Total</th>
      <th>Customer</th>
      <th>Employee</th>
      <th>Status</th>
      <th colspan="3"><h4><%= link_to '[New Sale]', new_sale_path %></h4>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td class="col-md-1"><%= sale.vehicle %></td>
        <td class="col-md-2"><%= number_to_currency(sale.total) %></td>
        <td class="col-md-2"><%= sale.customer.name %></td>
        <td class="col-md-2"><%= sale.employee.name %></td>
        <td><%= sale.status %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sales/new.html.erb
<h4>New Sale</h4>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @sale.vehicle %>
</p>

<p>
  <strong>Total:</strong>
  <%= number_to_currency(@sale.total) %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer.name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @sale.employee.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sale.status %>
</p>



<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', inventories_path %>